// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARXzfzU-XzMVKW0ezawnj8H-o68o0uxMg',
    appId: '1:473248840056:web:51bb1c61e5867b1022b08d',
    messagingSenderId: '473248840056',
    projectId: 'noteapp50',
    authDomain: 'noteapp50.firebaseapp.com',
    storageBucket: 'noteapp50.appspot.com',
    measurementId: 'G-Z2HL04H2XE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXu-1mbBs7jkXjNdDiMl-I0qmoOIPjrzw',
    appId: '1:473248840056:android:bf5be19b62d6147222b08d',
    messagingSenderId: '473248840056',
    projectId: 'noteapp50',
    storageBucket: 'noteapp50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDQL-k18pQyfdE-S9Fw-ShrpOfywjGlg',
    appId: '1:473248840056:ios:41cce69d024e590b22b08d',
    messagingSenderId: '473248840056',
    projectId: 'noteapp50',
    storageBucket: 'noteapp50.appspot.com',
    iosBundleId: 'com.example.noteapp50',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDQL-k18pQyfdE-S9Fw-ShrpOfywjGlg',
    appId: '1:473248840056:ios:5c793862866a969622b08d',
    messagingSenderId: '473248840056',
    projectId: 'noteapp50',
    storageBucket: 'noteapp50.appspot.com',
    iosBundleId: 'com.example.noteapp50.RunnerTests',
  );
}
